apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
      
      securityContext:
          fsGroup: 999
      
      containers:
        - name: postgres
          image: postgres:16.4-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_PASSWORD
            - name: POSTGRES_DB
              value: "AIaaS_Backend"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
          
          resources:
            limits:
              cpu: "1024m"            # Max CPU
              memory: "512Mi"         # Max memory
            requests:
              cpu: "250m"             # Requested CPU
              memory: "256Mi"         # Requested memory
      