apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
    app: database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/matze/workspaces/db_data/data"  # Adjust this path for cloud environments as needed
    type: Directory
